---
title: "DSlecture9"
author: "Hening cui"
date: "2021/10/7"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(patchwork)
```


```{r}
weather_df = 
  rnoaa::meteo_pull_monitors(
    c("USW00094728", "USC00519397", "USS0023B17S"),
    var = c("PRCP", "TMIN", "TMAX"), 
    date_min = "2017-01-01",
    date_max = "2017-12-31") %>%
  mutate(
    name = recode(
      id, 
      USW00094728 = "CentralPark_NY", 
      USC00519397 = "Waikiki_HA",
      USS0023B17S = "Waterhole_WA"),
    tmin = tmin / 10,
    tmax = tmax / 10) %>%
  select(name, id, everything())
weather_df
```

## remember this plot
```{r}
weather_df %>% 
  ggplot(aes(x = tmin, y = tmax, color = name)) +
  geom_point( alpha = 0.5)
```

## labels
```{r}
weather_df %>% 
  ggplot(aes(x = tmin, y = tmax, color = name)) +
  geom_point( alpha = 0.5) +
  labs(
    title = "t plot",
    x = "minimun daily(C)", 
    y = "maximum daily (C)",
    caption = "data from package"
  )
```

## scale
start with the same plot
```{r}
weather_df %>% 
  ggplot(aes(x = tmin, y = tmax, color = name)) +
  geom_point( alpha = 0.5) +
  labs(
    title = "t plot",
    x = "minimun daily(C)", 
    y = "maximum daily (C)",
    caption = "data from package"
  ) +
  scale_x_continuous(
    breaks = c(-15, 0, 15),
    labels = c("-15c", "0", "15C")
  ) +
  scale_y_continuous(
    trans = "sqrt",
    position ="right"
  )
```

color scales
```{r}
weather_df %>% 
  ggplot(aes(x = tmin, y = tmax, color = name)) +
  geom_point( alpha = 0.5) +
  labs(
    title = "t plot",
    x = "minimun daily(C)", 
    y = "maximum daily (C)",
    caption = "data from package"
  ) +
  scale_color_hue(
    name = "Location",
    h = c(100, 200))
```

```{r}
weather_df %>% 
  ggplot(aes(x = tmin, y = tmax, color = name)) +
  geom_point( alpha = 0.5) +
  labs(
    title = "t plot",
    x = "minimun daily(C)", 
    y = "maximum daily (C)",
    caption = "data from package"
  ) +
  viridis::scale_color_viridis(
    name = "location",
    discrete = TRUE)

```


